name: Chrome

on: [push]

jobs:
  Chrome:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: node-modules-1${{ hashFiles('package.json') }}

      - name: Install
        run: npm install

      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v3
        with:
          path: node_modules
          key: node-modules-1${{ hashFiles('package.json') }}

      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
